# Generated by Django 2.2.6 on 2019-10-31 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40, verbose_name='team_name')),
                ('area', models.CharField(max_length=40, verbose_name='title')),
                ('area_detail', models.CharField(max_length=40, verbose_name='title')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='일정')),
                ('discription', models.TextField(verbose_name='설명')),
                ('level_pass', models.IntegerField(default=0, verbose_name='패스_수준')),
                ('level_shoot', models.IntegerField(default=0, verbose_name='슛_수준')),
                ('level_dribble', models.IntegerField(default=0, verbose_name='드리블_수준')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='유저네임')),
            ],
        ),
    ]
