# Generated by Django 2.2.6 on 2019-10-31 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20191031_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='매니저네임'),
        ),
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('soccer', '축구'), ('foot', '족구'), ('basket', '농구')], max_length=10, verbose_name='sport_kind'),
        ),
        migrations.CreateModel(
            name='Basket_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_team_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_name', to='post.Basket_Team')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_member_user', to=settings.AUTH_USER_MODEL, verbose_name='용병_유저네임')),
            ],
        ),
    ]
