# Generated by Django 2.2.6 on 2019-10-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191031_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_team',
            name='level_dribble',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='드리블_수준'),
        ),
        migrations.AlterField(
            model_name='basket_team',
            name='level_pass',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='패스_수준'),
        ),
        migrations.AlterField(
            model_name='basket_team',
            name='level_shoot',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='슛_수준'),
        ),
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('soccer', '축구'), ('basket', '농구'), ('foot', '족구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
