# Generated by Django 2.2.6 on 2019-10-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191031_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_team',
            name='area',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='지역1'),
        ),
        migrations.AlterField(
            model_name='basket_team',
            name='area_detail',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='지역2'),
        ),
    ]
