# Generated by Django 2.2.6 on 2019-10-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191031_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_member',
            name='basket_team_names',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_names', to='post.Basket_Team'),
        ),
    ]
