# Generated by Django 2.2.6 on 2019-11-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20191031_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_team',
            name='max_people',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='모집인원'),
        ),
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('foot', '족구'), ('basket', '농구'), ('soccer', '축구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
