# Generated by Django 2.2.6 on 2019-11-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20191101_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('basket', '농구'), ('foot', '족구'), ('soccer', '축구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
