# Generated by Django 2.2.6 on 2019-11-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20191106_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('foot', '족구'), ('basket', '농구'), ('soccer', '축구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
