# Generated by Django 2.2.6 on 2019-11-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20191107_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_team',
            name='people_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='현재 지원 인원'),
        ),
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('foot', '족구'), ('soccer', '축구'), ('basket', '농구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
