# Generated by Django 2.2.6 on 2019-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20191107_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_team',
            name='people_count',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='현재 지원 인원'),
        ),
    ]
