# Generated by Django 2.2.6 on 2019-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20191107_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_team',
            name='level_defense',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수비_수준'),
        ),
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('basket', '농구'), ('foot', '족구'), ('soccer', '축구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
