# Generated by Django 2.2.6 on 2019-11-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20191107_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('soccer', '축구'), ('basket', '농구'), ('foot', '족구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
