# Generated by Django 2.2.6 on 2019-11-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20191031_1452'),
        ('post', '0017_auto_20191108_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_team',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='baske_place', to='first.Basket_place', verbose_name='경기장'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('soccer', '축구'), ('foot', '족구'), ('basket', '농구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
