# Generated by Django 2.2.6 on 2019-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20191108_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('basket', '농구'), ('foot', '족구'), ('soccer', '축구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
