# Generated by Django 2.2.6 on 2019-11-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20191108_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_team',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_place', to='first.Basket_place', verbose_name='경기장'),
        ),
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('soccer', '축구'), ('basket', '농구'), ('foot', '족구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
