# Generated by Django 2.2.6 on 2019-11-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20191108_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_team',
            name='place',
            field=models.CharField(max_length=40, verbose_name='경기장'),
        ),
        migrations.AlterField(
            model_name='mercenary',
            name='sport_kind',
            field=models.CharField(choices=[('foot', '족구'), ('soccer', '축구'), ('basket', '농구')], max_length=10, verbose_name='sport_kind'),
        ),
    ]
