# Generated by Django 2.2.6 on 2019-11-08 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0023_auto_20191108_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket_Team_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_basket_team_comments', to=settings.AUTH_USER_MODEL, verbose_name='유저네임')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Basket_Team')),
            ],
        ),
    ]
