# Generated by Django 2.2.6 on 2019-11-11 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_basket_team_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket_team_maching',
            name='sport_kind',
        ),
        migrations.RemoveField(
            model_name='basket_team_maching',
            name='team',
        ),
        migrations.AddField(
            model_name='basket_team_maching',
            name='team_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_maching', to='post.Basket_Team', verbose_name='팀_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket_team_maching',
            name='team_2',
            field=models.CharField(default=1, max_length=40, verbose_name='팀_2'),
            preserve_default=False,
        ),
    ]
