# Generated by Django 2.2.6 on 2019-11-11 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20191111_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket_team_maching_sinchung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_2', models.CharField(max_length=40, verbose_name='팀_2')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Basket_Team', verbose_name='팀_1')),
            ],
        ),
    ]
