# Generated by Django 2.2.6 on 2019-11-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_basket_team_maching_sinchung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_team_maching_sinchung',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_sinchung', to='post.Basket_Team', verbose_name='팀_1'),
        ),
    ]
