# Generated by Django 2.2.6 on 2019-11-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0029_auto_20191112_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_team_maching_sinchung',
            name='request_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mach_request_user', to=settings.AUTH_USER_MODEL, verbose_name='유저네임'),
            preserve_default=False,
        ),
    ]
