# Generated by Django 2.2.6 on 2019-11-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_basket_team_maching_sinchung_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket_team_maching_sinchung',
            name='request_user',
        ),
    ]
