# Generated by Django 2.2.6 on 2019-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_place',
            name='x_coor',
            field=models.CharField(default=0, max_length=40, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='basket_place',
            name='y_coor',
            field=models.CharField(default=0, max_length=40, verbose_name='경도'),
        ),
    ]
