# Generated by Django 2.2.6 on 2019-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20191029_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_place',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account/%Y/%m/%d', verbose_name='프로필 사진'),
        ),
    ]
