# Generated by Django 2.2.6 on 2019-10-30 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0003_basket_place_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_place',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='first/%Y/%m/%d', verbose_name='프로필 사진'),
        ),
        migrations.CreateModel(
            name='Place_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place_comments', to=settings.AUTH_USER_MODEL, verbose_name='유저네임')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Basket_place')),
            ],
        ),
    ]
