# Generated by Django 2.2.6 on 2019-10-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20191030_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket_place',
            old_name='description',
            new_name='discription',
        ),
    ]
